apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-production-http
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ required "The 'email' value must be set!" .Values.email }}
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - http01:
        ingress: {}
